# composed as MMmmRRbb where:
# MM = Major (incremented when app is released to production)
# mm = minor (incremented when app is released to customer)
# RR = release (incremented when breaking change is implemented)
# bb = build (incremented when build is made for internal testers)
version.major=0
version.minor=1
version.release=0
version.build=0
